# Generated by Django 4.1.4 on 2022-12-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
    ]
