# Generated by Django 4.1.4 on 2022-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_employees_salary_alter_teachers_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employees',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
    ]
